-- MySQL Script generated by MySQL Workbench
-- mer. 08 déc. 2021 21:53:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Slake
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Slake
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Slake` DEFAULT CHARACTER SET utf8 ;
USE `Slake` ;

-- -----------------------------------------------------
-- Table `Slake`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Slake`.`Message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `Room_idRoom` INT NOT NULL,
  `user_source` INT NOT NULL,
  `user_destination` INT NOT NULL,
  PRIMARY KEY (`idMessage`, `Room_idRoom`),
  INDEX `fk_Message_Room1_idx` (`Room_idRoom` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`user_source` ASC) VISIBLE,
  INDEX `fk_Message_User2_idx` (`user_destination` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `Slake`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`user_source`)
    REFERENCES `Slake`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User2`
    FOREIGN KEY (`user_destination`)
    REFERENCES `Slake`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Slake`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Slake`.`Room` (
  `idRoom` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `userCounter` INT NOT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Slake`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Slake`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Slake`.`User_has_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Slake`.`User_has_Room` (
  `User_idUser` INT NOT NULL AUTO_INCREMENT,
  `Room_idRoom` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Room_idRoom`),
  INDEX `fk_User_has_Room_Room1_idx` (`Room_idRoom` ASC) VISIBLE,
  INDEX `fk_User_has_Room_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Room_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Slake`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Room_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `Slake`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
